spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          search-locations: "file:///C://Users//Thais//Documents//study//microservices-spring//config"
server:
  port: 8071
